version: "3.8"
services:
  pocketbase:
    build: fin-app-backend
    container_name: pocketbase
    ports:
      - "8080:8080"
    volumes:
      - pocketbase-data:/pb_data
volumes:
  pocketbase-data:
